const router = require('express').Router();
// const expressValidator = require('express-validator');
const fs = require('fs');
const words = fs.readFileSync("/usr/share/dict/words", "utf-8").toLowerCase().split("\n");

// Fake Database
var computerChoice = " ";  // stores word that computer guesses
var userGuess = [];   // stores characters user chooses
var count = 8;         // stores amout of times user can play ( 8 times)
var display = [];       // this is the display
let input;
let winOrlose = [];


router.use('/', function(req, res, next){
    req.newThing = {
        item: "im on the request now"
    }
    next();
})

router.get('/', function (req, res) {

    
    // checks to see if computer has chosen a random alpahbet
    if (computerChoice === " ") {

        console.log('Computer time to pick a word');
        var randomNum = words[Math.floor(Math.random() * 3000)];
        computerChoice = randomNum;
        winOrlose = [];

        for (let i = 0; i < computerChoice.length; i++) {
            display.push("_");
        };

        res.redirect('/');
    } else {



        // checks to see if user has used up all turns by finding if the count is 0. If the count is greater than zero game resumes, if not game is over;
        if (count === 0) {
            
            console.log('game over');
            winOrlose.push( "Sorry, you lose.");
            // sets count back to 8
            userGuess = []; //emptys userGuess array

            // computerChoice.splice(0, 1); // deletes random word generated by computer from array
            computerChoice = " ";
            display = [];

            count = 8;
            res.render('home', { userGuess, count, display, winOrlose });
            

        } else if(computerChoice === display.join('').toString()) {
            console.log('You won');
            winOrlose.push("YESSSS, you won!!!");
            
            userGuess = []; //emptys userGuess array

            // computerChoice.splice(0, 1); // deletes random word generated by computer from array
            computerChoice = " ";
            display = [];

            count = 8;
           res.render('home', { userGuess, count, display, winOrlose });
            

        } else {
            console.log(computerChoice);
          
            res.render('home', { userGuess, count, display, winOrlose });
        }

    }

});



router.post('/', function (req, res) {
    req.checkBody('input', 'you can only enter one letter at a time').len(0, 1);
    req.checkBody('input', 'you have to enter a value').notEmpty();

    input = req.body.input;

    var errors = req.validationErrors();

    // check if their are errors if not keep going
    if (errors) {
        res.render('home', { errors: errors });
        return;
    } else {

        console.log("-----------------------------");
        // normal processing here
        console.log('You picked a new letter. You are at ' + req.url);


        req.session.choice = input;


        // if user input matches whats in computerChoice
        if (computerChoice.includes(input)) {

            // iterate over computerChoice to get every instance of user input
            for (let i = 0; i < computerChoice.length; i++) {
                let computerGuess = computerChoice.split('');
                
                // if the specific index in computerGuess equals user input 
                if (computerGuess[i] === input) {
                    console.log('--------- finding the index');
                    display.splice(i,1,input);
                }

            }


            userGuess.push(req.session.choice);

            console.log("display now has the following values of: " + display);
            console.log('user guess has the following values: ' + userGuess);

            res.redirect('/')


        } else {
            console.log('you picked the wrong letter');
            count--;

            userGuess.push(req.session.choice);
            // display.push(userGuess.filter(wordsMatch));
            console.log("display now has the following values of: " + display);
            console.log('user guess has the following values: ' + userGuess);

            res.redirect('/')
        }


    }
});





module.exports = router;